package com.znaji.event_ticket_platform.common.mapping.events;

import com.znaji.event_ticket_platform.api.events.AddTicketTypeRequest;
import com.znaji.event_ticket_platform.api.events.CreateEventRequest;
import com.znaji.event_ticket_platform.api.events.UpdateTicketTypeRequest;
import com.znaji.event_ticket_platform.application.events.AddTicketTypeCommand;
import com.znaji.event_ticket_platform.application.events.CreateEventCommand;
import com.znaji.event_ticket_platform.application.events.UpdateTicketTypeCommand;
import com.znaji.event_ticket_platform.domain.events.Event;
import com.znaji.event_ticket_platform.domain.events.EventStatus;
import com.znaji.event_ticket_platform.domain.events.TicketType;

import java.util.UUID;

public final class EventMapper {

    private EventMapper() {
        // Utility class
    }

    public static Event toEntity(CreateEventCommand cmd) {
        Event event = new Event();

        event.setId(null); // id generated by JPA
        event.setOrganizerId(cmd.organizerId());
        event.setName(cmd.name());
        event.setDescription(cmd.description());
        event.setStart(cmd.start());
        event.setEnd(cmd.end());
        event.setVenue(cmd.venue());

        event.setStatus(EventStatus.DRAFT);

        return event;
    }

    public static TicketType toEntity(AddTicketTypeCommand cmd, Event event) {
        TicketType ticketType = new TicketType();

        ticketType.setName(cmd.name());
        ticketType.setPrice(cmd.price());
        ticketType.setMaxQuantity(cmd.maxQuantity());
        ticketType.setSoldQuantity(0);      // new ticket type always starts with zero sold
        ticketType.setEvent(event);         // associate with already-loaded Event

        return ticketType;
    }

    public static CreateEventCommand toCommand(CreateEventRequest request) {
        if (request == null) {
            return null;
        }

        return new CreateEventCommand(
                request.organizerId(),
                request.name(),
                request.description(),
                request.start(),
                request.end(),
                request.venue()
        );
    }

    public static AddTicketTypeCommand toCommand(UUID eventId, AddTicketTypeRequest request) {
        if (request == null) {
            return null;
        }

        return new AddTicketTypeCommand(
                eventId,
                request.name(),
                request.price(),
                request.maxQuantity()
        );
    }

    public static UpdateTicketTypeCommand toCommand(
            UUID eventId,
            UUID ticketTypeId,
            UpdateTicketTypeRequest request
    ) {
        if (request == null) {
            return null;
        }

        return new UpdateTicketTypeCommand(
                eventId,
                ticketTypeId,
                request.name(),
                request.price(),
                request.maxQuantity()
        );
    }
}
