package com.znaji.event_ticket_platform.application.events;

import com.znaji.event_ticket_platform.domain.events.Event;
import com.znaji.event_ticket_platform.domain.events.EventStatus;
import com.znaji.event_ticket_platform.domain.events.TicketType;

public final class EventMapper {

    private EventMapper() {
        // Utility class
    }

    public static Event toEntity(CreateEventCommand cmd) {
        Event event = new Event();

        event.setId(null); // id generated by JPA
        event.setOrganizerId(cmd.organizerId());
        event.setName(cmd.name());
        event.setDescription(cmd.description());
        event.setStart(cmd.start());
        event.setEnd(cmd.end());
        event.setVenue(cmd.venue());

        event.setStatus(EventStatus.DRAFT);

        return event;
    }

    public static TicketType toEntity(AddTicketTypeCommand cmd, Event event) {
        TicketType ticketType = new TicketType();

        ticketType.setName(cmd.name());
        ticketType.setPrice(cmd.price());
        ticketType.setMaxQuantity(cmd.maxQuantity());
        ticketType.setSoldQuantity(0);      // new ticket type always starts with zero sold
        ticketType.setEvent(event);         // associate with already-loaded Event

        return ticketType;
    }
}
